language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
    - master
cache:
  directories:
    - node_modules

deploy:
  # deploy app as api server
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure:73b5c1ce-ce2c-453e-b975-362abe7d8922
    app: angular-challenge-api

after_deploy:
  # Procfile is only used for client, delete it to let server run 'npm start'
  - rm Procfile